const {test,beforeEach,afterEach}=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const {Readable}=require('node:stream');
const billing=require('../lib/billing');
const webhook=require('../api/webhook');
const access=require('../api/access');
const search=require('../api/search');
const originalFetch=global.fetch;
const originalEnv={...process.env};
beforeEach(()=>{Object.assign(process.env,{VERCEL_ENV:'preview',STRIPE_SECRET_KEY:'sk_test_fixture',URENAVI_PRICE_ID:'price_test',URENAVI_PAYMENT_LINK_ID:'plink_test',URENAVI_PAYMENT_LINK_URL:'https://buy.stripe.com/test_fixture',SUPABASE_SERVICE_ROLE_KEY:'fixture',STRIPE_WEBHOOK_SECRET:'fixture'});});
afterEach(()=>{global.fetch=originalFetch; for(const key of Object.keys(process.env)) if(!(key in originalEnv)) delete process.env[key];Object.assign(process.env,originalEnv);});
const response=data=>({ok:true,status:200,json:async()=>data});
const sub=(extra={})=>({id:'sub_test',customer:'cus_test',livemode:false,status:'active',items:{data:[{price:{id:'price_test'},current_period_end:Math.floor(Date.now()/1000)+3600}]},...extra});
function res(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(body){this.body=body;return this;},end(){return this;},redirect(n,url){this.code=n;this.url=url;return this;}};}
function signed(event,secret='fixture'){const body=Buffer.from(JSON.stringify(event));const t=Math.floor(Date.now()/1000);const sig=crypto.createHmac('sha256',secret).update(t+'.').update(body).digest('hex');const req=Readable.from([body]);req.method='POST';req.headers={'stripe-signature':`t=${t},v1=${sig}`};return req;}
test('Preview refuses absent config and LIVE key/link',()=>{delete process.env.URENAVI_PRICE_ID;assert.throws(billing.config);process.env.URENAVI_PRICE_ID='price_test';process.env.STRIPE_SECRET_KEY='sk_live_fixture';assert.throws(billing.config);process.env.STRIPE_SECRET_KEY='sk_test_fixture';process.env.URENAVI_PAYMENT_LINK_URL='https://buy.stripe.com/live';assert.throws(billing.config);});
test('Production refuses TEST key',()=>{process.env.VERCEL_ENV='production';assert.throws(billing.config);});
test('Only active, matching mode/price, future paid period allows access',()=>{assert.equal(billing.subscriptionState(sub()).active,true);for(const status of ['canceled','past_due','unpaid','incomplete','incomplete_expired','paused','trialing'])assert.equal(billing.subscriptionState(sub({status})).active,false);assert.equal(billing.subscriptionState(sub({livemode:true})).active,false);assert.equal(billing.subscriptionState(sub({items:{data:[]}})).active,false);assert.equal(billing.subscriptionState(sub({items:{data:[{price:{id:'price_test'},current_period_end:1}]}})).active,false);});
test('Period-end cancellation allows already paid period; canceled blocks immediately',()=>{assert.equal(billing.subscriptionState(sub({cancel_at_period_end:true})).active,true);assert.equal(billing.subscriptionState(sub({status:'canceled',cancel_at_period_end:true})).active,false);});
test('Webhook rejects tamper, missing secret, replay and malformed signatures',()=>{const raw=Buffer.from('{}'),t=1000;const hash=crypto.createHmac('sha256','fixture').update(t+'.').update(raw).digest('hex');assert.deepEqual(billing.verifySignature(raw,`t=${t},v1=${hash}`,'fixture',t),{});for(const args of [[Buffer.from('{ }'),`t=${t},v1=${hash}`,'fixture',t],[raw,`t=${t},v1=${hash}`,'',t],[raw,`t=${t},v1=${hash}`,'fixture',t+301],[raw,`t=${t},v1=abc`,'fixture',t]])assert.throws(()=>billing.verifySignature(...args));});
test('Wrong-mode webhook cannot call services',async()=>{global.fetch=()=>{throw new Error('must not fetch');};const r=res();await webhook(signed({livemode:true,type:'customer.subscription.deleted',data:{object:{id:'sub_test'}}}),r);assert.equal(r.code,400);});
test('Signed cancellation fetches current state and synchronizes isolated row; repeats are safe',async()=>{const writes=[];global.fetch=async(url,options)=>{url=String(url);if(url.includes('/subscriptions/'))return response(sub({status:'canceled'}));if(url.includes('/customers/'))return response({email:'Buyer@example.com'});if(url.includes('rpc/urenavi_sync_entitlement')){writes.push(JSON.parse(options.body).p_row);return response(null);}return response([]);};const event={livemode:false,type:'customer.subscription.deleted',data:{object:{id:'sub_test'}}};for(let i=0;i<2;i++){const r=res();await webhook(signed(event),r);assert.equal(r.code,200);}assert.equal(writes.length,2);assert.equal(writes[0].active,false);assert.equal(writes[0].livemode,false);assert.equal(writes[0].email,'buyer@example.com');});
test('Webhook database failure remains retryable without leaking secret',async()=>{global.fetch=async()=>{throw new Error('sk_test_DO_NOT_EXPOSE');};const r=res();await webhook(signed({livemode:false,type:'customer.subscription.updated',data:{object:{id:'sub_test'}}}),r);assert.equal(r.code,503);assert.ok(!JSON.stringify(r).includes('DO_NOT_EXPOSE'));});
test('Unpaid checkout never provisions access',async()=>{global.fetch=async()=>response({livemode:false,mode:'subscription',status:'complete',payment_status:'unpaid',payment_link:'plink_test',subscription:'sub_test'});await assert.rejects(()=>billing.activate('cs_test_fixture'));});
test('Access and search reject missing authentication before external fetch',async()=>{global.fetch=()=>{throw new Error('must not fetch');};for(const handler of [access,search]){const r=res();await handler({method:'GET',headers:{},query:{action:'status',keyword:'充電器'}},r);assert.equal(r.code,401);assert.equal(r.headers['Cache-Control'],'no-store');}});
function authToken(){return 'header.'+Buffer.from(JSON.stringify({sub:'user_fixture',session_id:'00000000-0000-0000-0000-000000000001'})).toString('base64url')+'.signature';}
test('Expired/revoked session rejected even if user recently signed in elsewhere',async()=>{global.fetch=async url=>String(url).includes('/auth/v1/user')?response({id:'user_fixture',email:'a@example.com',last_sign_in_at:new Date().toISOString()}):response(false);assert.deepEqual(await billing.authorize({headers:{authorization:'Bearer '+authToken()}}),{ok:false,status:401});});
test('Preview rejects legacy paid subscriptions while allowing the explicit active owner',async()=>{
  const calls=[];
  let legacy=[{status:'active',active:true,stripe_subscription_id:'sub_live'}];
  global.fetch=async url=>{
    url=String(url);calls.push(url);
    if(url.includes('/auth/v1/user'))return response({id:'user_fixture',email:'a@example.com'});
    if(url.includes('urenavi_session_valid'))return response(true);
    if(url.includes('urenavi_entitlements?'))return response(legacy);
    if(url.includes('urenavi_entitlements_v2?'))return response([]);
    throw new Error('Unexpected service request');
  };
  const request={headers:{authorization:'Bearer '+authToken()}};
  assert.equal((await billing.authorize(request)).status,403);
  assert.ok(calls.some(x=>x.includes('livemode=eq.false')));
  assert.ok(!calls.some(x=>x.includes('/subscriptions/')));
  legacy=[{status:'owner',active:false}];
  assert.equal((await billing.authorize(request)).status,403);
  legacy=[{status:'owner',active:true}];
  assert.equal((await billing.authorize(request)).ok,true);
});
test('Paid user direct access checks actual Stripe state',async()=>{global.fetch=async url=>{url=String(url);if(url.includes('/auth/v1/user'))return response({id:'user_fixture',email:'a@example.com'});if(url.includes('urenavi_session_valid'))return response(true);if(url.includes('/subscriptions/'))return response(sub());return response([{stripe_subscription_id:'sub_test'}]);};assert.equal((await billing.authorize({headers:{authorization:'Bearer '+authToken()}})).ok,true);});
test('Buy verifies 980 JPY monthly, 30 checkout cap and activation destination',async()=>{process.env.URENAVI_APP_URL='https://preview.example.com';const link={livemode:false,active:true,url:process.env.URENAVI_PAYMENT_LINK_URL,restrictions:{completed_sessions:{limit:30,count:0}},after_completion:{type:'redirect',redirect:{url:'https://preview.example.com/api/access?action=activate&session_id={CHECKOUT_SESSION_ID}'}}};const price={id:'price_test',unit_amount:980,currency:'jpy',recurring:{interval:'month',interval_count:1}};global.fetch=async url=>response(String(url).includes('/line_items')?{data:[{quantity:1,price}]}:link);let r=res();await access({method:'GET',headers:{},query:{action:'buy'}},r);assert.equal(r.code,302);for(const mutate of [()=>{link.restrictions.completed_sessions.limit=31;},()=>{link.restrictions.completed_sessions.limit=30;price.unit_amount=1980;},()=>{price.unit_amount=980;link.after_completion.redirect.url='https://production.example.com/app.html';}]){mutate();r=res();await access({method:'GET',headers:{},query:{action:'buy'}},r);assert.equal(r.code,503);}});
test('Search ranks relevant products and returns finite sellability/profitability and affiliate URLs',async()=>{process.env.RAKUTEN_APP_ID='fixture';process.env.RAKUTEN_ACCESS_KEY='fixture';process.env.RAKUTEN_AFFILIATE_ID='fixture';global.fetch=async url=>{url=String(url);if(url.includes('/auth/v1/user'))return response({id:'user_fixture',email:'a@example.com'});if(url.includes('urenavi_session_valid'))return response(true);if(url.includes('/subscriptions/'))return response(sub());if(url.includes('urenavi_entitlements_v2'))return response([{stripe_subscription_id:'sub_test'}]);if(url.includes('urenavi_entitlements?'))return response([]);assert.ok(url.startsWith('https://openapi.rakuten.co.jp/'));return response({items:[{itemName:'充電器 USB-C',itemPrice:3000,reviewCount:100,reviewAverage:4.5,affiliateRate:4,itemUrl:'https://item.rakuten.co.jp/fixture/usb-c-charger/',affiliateUrl:'https://hb.afl.rakuten.co.jp/fixture',mediumImageUrls:['https://example.com/image.png']},{itemName:'ふるさと納税 充電器',itemPrice:30000,reviewCount:1000,reviewAverage:5,affiliateRate:4}],count:2});};const r=res();await search({headers:{authorization:'Bearer '+authToken()},query:{keyword:'充電器'}},r);assert.equal(r.code,200);assert.equal(r.body.items.length,1);const item=r.body.items[0];for(const key of ['sellability','profitability','score'])assert.ok(Number.isFinite(item[key])&&item[key]>=0&&item[key]<=100);assert.equal(item.estimatedCommission,120);assert.ok(item.affiliateUrl.startsWith('https://hb.afl.rakuten.co.jp/'));assert.equal(item.roomItemUrl,'https://item.rakuten.co.jp/fixture/usb-c-charger/');});

test('Delayed checkout event after cancellation acknowledges current inactive state',async()=>{let written;global.fetch=async(url,options)=>{url=String(url);if(url.includes('/checkout/sessions/'))return response({livemode:false,mode:'subscription',status:'complete',payment_status:'paid',payment_link:'plink_test',subscription:'sub_test'});if(url.includes('/subscriptions/'))return response(sub({status:'canceled'}));if(url.includes('/customers/'))return response({email:'a@example.com'});if(url.includes('rpc/urenavi_sync_entitlement')){written=JSON.parse(options.body).p_row;return response(null);}return response([]);};const r=res();await webhook(signed({livemode:false,type:'checkout.session.completed',data:{object:{id:'cs_test_fixture',payment_link:'plink_test',payment_status:'paid'}}}),r);assert.equal(r.code,200);assert.equal(written.active,false);});
