'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {analyzeProductV3}=require('../lib/super-urenavi-v3-engine');
const {createHandler}=require('../api/room-ai-v3');
const item={itemCode:'recovery:1',itemName:'収納ボックス 積み重ね可能',itemCaption:'積み重ね可能'};
const good={productType:{specific:'収納ボックス',general:'収納用品',quote:'収納ボックス'},attributes:[{name:'使い方',value:'積み重ね可能',quote:'積み重ね可能'}],appeals:[{text:'縦にまとめて収納したいときに',attributeRefs:[0],strength:3}],hooks:[{type:'scene',text:'床に物が広がって置き場所に迷うときに。'}]};
const weak={...good,appeals:[],hooks:[]};const pass2={results:[{verificationIndex:0,supported:true,keepDirectFact:true,reason:'supported'}]};
function memory(){let row;return{loadProduct:async()=>row,saveProduct:async x=>{row={schema_version:x.schemaVersion,raw_ai_json:structuredClone(x.rawAiJson)};},read:()=>row};}
function limited(){const e=new Error('limited');e.status=429;e.retryAfterMs=60000;e.quotaSource='groq';return e;}
test('429 during quality retry preserves understanding, counts failed call, resumes retry only',async()=>{const store=memory();let calls=0;const run=()=>analyzeProductV3({item,store,callPass1:async()=>{calls++;if(calls===1)return {raw:weak};if(calls===2)throw limited();return{raw:good};},callPass2:async()=>({raw:pass2})});await assert.rejects(run,e=>e.stage==='quality_retry'&&e.groq.totalCalls===2&&e.groq.qualityRetryCalls===1);assert.ok(store.read().raw_ai_json.pass1);const resumed=await run();assert.equal(calls,3);assert.equal(resumed.groq.pass1Calls,1);assert.equal(resumed.groq.qualityRetryCalls,1);assert.equal(resumed.qualityGate.ready,true);const cached=await run();assert.equal(cached.groq.totalCalls,0);assert.equal(calls,3);});
test('429 during verification does not repeat understanding and never stores failed verification',async()=>{const store=memory();let p1=0,p2=0;const run=()=>analyzeProductV3({item,store,callPass1:async()=>{p1++;return{raw:good};},callPass2:async()=>{p2++;if(p2===1)throw limited();return{raw:pass2};}});await assert.rejects(run,e=>e.stage==='pass2'&&e.groq.totalCalls===2);assert.equal(store.read().raw_ai_json.pass2,null);const resumed=await run();assert.equal(p1,1);assert.equal(resumed.groq.pass1Calls,0);assert.equal(resumed.groq.pass2Calls,1);assert.equal((await run()).groq.totalCalls,0);});
test('quota denial is not counted as a Groq HTTP request',async()=>{const store=memory();await assert.rejects(()=>analyzeProductV3({item,store,consumeQuota:async()=>false,callPass1:async()=>{throw Error('must not call');}}),e=>e.quotaSource==='urenavi'&&e.groq.totalCalls===0);assert.equal(store.read(),undefined);});
test('a cached understanding survives prompt/schema revision with zero calls',async()=>{const store={loadProduct:async()=>({schema_version:'super_urenavi_v3_understanding_v5_targeted_quality_retry',raw_ai_json:{pass1:good,pass2}}),saveProduct:async()=>{throw Error('unexpected write');}};const r=await analyzeProductV3({item,store,callPass1:async()=>{throw Error('unexpected call');}});assert.equal(r.groq.totalCalls,0);});
test('evaluation endpoint keeps owner authentication and production isolation',async()=>{const old=process.env.VERCEL_ENV;process.env.VERCEL_ENV='preview';try{const handler=createHandler({authorize:async()=>({ok:false}),store:memory(),groq:{callPass1:async()=>{throw Error('unexpected call');}}});const res={status(n){this.code=n;return this;},setHeader(){},json(d){this.body=d;return this;}};await handler({method:'POST',body:item},res);assert.equal(res.code,403);process.env.VERCEL_ENV='production';await handler({method:'POST',body:item},res);assert.equal(res.code,404);assert.equal(require('../api/v3-eval-ai'),require('../api/room-ai-v3'));}finally{if(old===undefined)delete process.env.VERCEL_ENV;else process.env.VERCEL_ENV=old;}});
