'use strict';
const assert=require('node:assert/strict');
const {createV3Groq,capCaption,retryDelayMs,isRetryableRateLimit}=require('../lib/super-urenavi-v3-groq');
function response(payload,{status=200,headers={}}={}){return {ok:status>=200&&status<300,status,headers:{get(name){return headers[String(name).toLowerCase()]??null;}},async json(){return payload;}};}
(async()=>{
 const calls=[];const fetchImpl=async(url,opts)=>{calls.push({url,body:JSON.parse(opts.body)});return response({model:'mock',usage:{input_tokens:10,output_tokens:20},output_text:JSON.stringify({productType:{specific:'電気ケトル',general:'ケトル',quote:'電気ケトル'},attributes:[],decisionAxes:[],appeals:[],hooks:[]})});};
 const groq=createV3Groq({apiKey:'test',model:'mock',fetchImpl});const p1=await groq.callPass1({item:{itemName:'電気ケトル',itemCaption:'説明'.repeat(1000),itemPrice:1000}});assert.equal(p1.raw.productType.specific,'電気ケトル');assert.equal(calls.length,1);assert.equal(calls[0].body.reasoning.effort,'none');assert.equal(calls[0].body.text.format.strict,true);assert.equal(calls[0].body.text.format.name,'super_urenavi_v3_understanding');assert.equal(calls[0].body.max_output_tokens,900);const pass1User=JSON.parse(calls[0].body.input[1].content[0].text);assert.ok(pass1User.itemCaption.length<=1200);assert.deepEqual(Object.keys(groq),['callPass1']);
 let plainCalls=0;const plain=createV3Groq({apiKey:'test',model:'mock',fetchImpl:async()=>{plainCalls++;return response({error:{type:'rate_limit_error',message:'limited'}},{status:429});}});await assert.rejects(()=>plain.callPass1({item:{itemName:'x'}}),e=>e?.status===429);assert.equal(plainCalls,1);
 let retryCalls=0;const retrying=createV3Groq({apiKey:'test',model:'mock',fetchImpl:async()=>{retryCalls++;return response({error:{code:'rate_limit_exceeded',message:'Rate limit reached. Please try again in 0.001s.'}},{status:429});}});await assert.rejects(()=>retrying.callPass1({item:{itemName:'電気ケトル'}}),e=>e.status===429&&e.retryAfterMs>0);assert.equal(retryCalls,1);
 const r=response({}, {status:429});assert.ok(retryDelayMs(r,{error:{message:'Please try again in 1.5s.'}})>=1500);assert.equal(isRetryableRateLimit(r,{error:{code:'rate_limit_exceeded',message:'Please try again in 1ms.'}}),true);assert.ok(capCaption('a'.repeat(5000)).length<=1200);console.log('super-urenavi-v3-groq.test.js: PASS');
})().catch(error=>{console.error(error);process.exitCode=1;});
